<center><h1>Escenarios experimentales Internetworking</h1></center>

Presentado por: Holger Fernando Catucuamba Nepas <br>
Fecha: 23/02/2023

##  Importación de librerias necesarias

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Cargar el Dataset

In [2]:
datapath = 'https://raw.githubusercontent.com/hfcatucuamba/proyectoInternetworking/main/Escenario3.csv'
names = ['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Stime', 'Ltime', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat', 'label']
dataframe = pd.read_csv(datapath,names=names,low_memory=False, sep=';')

In [3]:
dataframe.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,label
0,59.166.0.9,7045,149.171.126.7,25,tcp,FIN,0.201886,37552,3380,31,...,,2,2,7,4,1,1,3,NaN,0
1,59.166.0.9,9685,149.171.126.2,80,tcp,FIN,5.864.748,19410,1087890,31,...,,3,1,4,4,1,1,1,NaN,0
2,59.166.0.2,1421,149.171.126.4,53,udp,CON,0.001391,146,178,31,...,,3,5,2,7,1,1,4,NaN,0
3,59.166.0.2,21553,149.171.126.2,25,tcp,FIN,0.053948,37812,3380,31,...,,1,1,4,7,1,1,3,NaN,0
4,59.166.0.8,45212,149.171.126.4,53,udp,CON,0.000953,146,178,31,...,,2,5,2,1,1,1,2,NaN,0

### Descripción del problema

In [4]:
dataframe.describe()

,sport,sbytes,dbytes,sttl,dttl,sloss,dloss,Spkts,Dpkts,swin,...,ct_flw_http_mthd,is_ftp_login,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,label
count,3000.00000,3.000000e+03,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,...,621.000000,82.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,32747.94900,8.475333e+03,3.095792e+04,110.831333,110.269000,6.288333,14.102333,30.912000,36.679333,184.025000,...,1.096618,1.073171,4.399667,4.12000,2.647667,2.994000,1.467333,1.029333,3.257000,0.500000
std,19863.14715,6.575680e+04,1.593243e+05,102.249355,111.227103,25.673714,56.775326,75.075755,119.951826,114.304547,...,0.530068,0.465620,6.023235,5.88437,2.324650,2.624295,1.804444,0.210921,5.638813,0.500083
min,0.00000,4.600000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,15253.75000,5.640000e+02,2.680000e+02,31.000000,29.000000,0.000000,0.000000,4.000000,4.000000,0.000000,...,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,33027.50000,1.251000e+03,1.231000e+03,62.000000,29.000000,2.000000,2.000000,10.000000,8.000000,255.000000,...,1.000000,1.000000,2.000000,2.00000,2.000000,2.000000,1.000000,1.000000,2.000000,0.500000
75%,50372.75000,2.934000e+03,1.016800e+04,254.000000,252.000000,7.000000,9.000000,38.000000,34.000000,255.000000,...,1.000000,1.000000,6.000000,5.00000,4.000000,4.000000,1.000000,1.000000,3.000000,1.000000
max,65532.00000,2.654524e+06,2.374900e+06,254.000000,252.000000,999.000000,895.000000,2004.000000,1796.000000,255.000000,...,4.000000,4.000000,36.000000,36.00000,16.000000,16.000000,16.000000,4.000000,36.000000,1.000000

## Normalizar los datos

In [5]:
columna_a_codificar = dataframe['srcip']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['srcip'] = columna_codificada

In [6]:
columna_a_codificar = dataframe['dstip']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['dstip'] = columna_codificada

In [7]:
columna_a_codificar = dataframe['dsport']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['dsport'] = columna_codificada

In [8]:
columna_a_codificar = dataframe['proto']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['proto'] = columna_codificada

In [9]:
columna_a_codificar = dataframe['state']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['state'] = columna_codificada

In [10]:
columna_a_codificar = dataframe['dur']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['dur'] = columna_codificada

In [11]:
columna_a_codificar = dataframe['service']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['service'] = columna_codificada

In [12]:
columna_a_codificar = dataframe['Sload']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Sload'] = columna_codificada

In [13]:
columna_a_codificar = dataframe['Dload']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Dload'] = columna_codificada

In [14]:
columna_a_codificar = dataframe['Sjit']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Sjit'] = columna_codificada

In [15]:
columna_a_codificar = dataframe['Djit']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Djit'] = columna_codificada

In [16]:
columna_a_codificar = dataframe['Sintpkt']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Sintpkt'] = columna_codificada

In [17]:
columna_a_codificar = dataframe['Dintpkt']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['Dintpkt'] = columna_codificada

In [18]:
columna_a_codificar = dataframe['ct_ftp_cmd']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['ct_ftp_cmd'] = columna_codificada

In [19]:
columna_a_codificar = dataframe['attack_cat']
le = LabelEncoder()
columna_codificada = le.fit_transform(columna_a_codificar)
dataframe['attack_cat'] = columna_codificada

## Separar las características del conjunto de datos en una matriz separada

In [20]:
X = dataframe.iloc[:, :-1].values
scaler = StandardScaler()
x_normalised = scaler.fit_transform(X)
y = dataframe['label']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x_normalised,
                                            y, test_size=0.3, random_state=42)

## Crear Modelo

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.constraints import MaxNorm
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    Conv1D(64, 3, input_shape=(X_train.shape[1], 1), padding="same", activation="relu", kernel_constraint=MaxNorm(3)),
    Dropout(0.3),
    Conv1D(64, 3, padding="same", activation="relu", kernel_constraint=MaxNorm(3)),
    Flatten(),
    Dense(512, activation="relu", kernel_constraint=MaxNorm(3)),
    Dropout(0.3),
    Dense(10, activation="softmax")
])

model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy", 
              metrics=["sparse_categorical_accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d (Conv1D)             (None, 48, 64)            256

 dropout (Dropout)           (None, 48, 64)            0

 conv1d_1 (Conv1D)           (None, 48, 64)            12352

 flatten (Flatten)           (None, 3072)              0

 dense (Dense)               (None, 512)               1573376

 dropout_1 (Dropout)         (None, 512)               0

 dense_1 (Dense)             (None, 10)                5130

=================================================================
Total params: 1,591,114
Trainable params: 1,591,114
Non-trainable params: 0
_________________________________________________________________

In [23]:
batch_size = 32
steps_per_epoch = (X_train.shape[0]//batch_size)
validation_steps = (x_normalised.shape[0] // batch_size)

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=200)

In [24]:
%%time

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=35, batch_size=32)

Epoch 1/35
66/66 [==============================] - 3s 27ms/step - loss: 2.2519 - sparse_categorical_accuracy: 0.4824 - val_loss: 2.1999 - val_sparse_categorical_accuracy: 0.5211
Epoch 2/35
66/66 [==============================] - 1s 15ms/step - loss: 2.1514 - sparse_categorical_accuracy: 0.4910 - val_loss: 2.1016 - val_sparse_categorical_accuracy: 0.5211
Epoch 3/35
66/66 [==============================] - 1s 15ms/step - loss: 2.0554 - sparse_categorical_accuracy: 0.4910 - val_loss: 2.0078 - val_sparse_categorical_accuracy: 0.5211
Epoch 4/35
66/66 [==============================] - 1s 15ms/step - loss: 1.9639 - sparse_categorical_accuracy: 0.4910 - val_loss: 1.9187 - val_sparse_categorical_accuracy: 0.5211
Epoch 5/35
66/66 [==============================] - 1s 16ms/step - loss: 1.8771 - sparse_categorical_accuracy: 0.4681 - val_loss: 1.8345 - val_sparse_categorical_accuracy: 0.5211
Epoch 6/35
66/66 [==============================] - 1s 14ms/step - loss: 1.7952 - sparse_categorical_accuracy: 0.4824 - val_loss: 1.7550 - val_sparse_categorical_accuracy: 0.5211
Epoch 7/35
66/66 [==============================] - 1s 14ms/step - loss: 1.7181 - sparse_categorical_accuracy: 0.4900 - val_loss: 1.6804 - val_sparse_categorical_accuracy: 0.5211
Epoch 8/35
66/66 [==============================] - 1s 14ms/step - loss: 1.6458 - sparse_categorical_accuracy: 0.5014 - val_loss: 1.6105 - val_sparse_categorical_accuracy: 0.4789
Epoch 9/35
66/66 [==============================] - 1s 14ms/step - loss: 1.5782 - sparse_categorical_accuracy: 0.4852 - val_loss: 1.5453 - val_sparse_categorical_accuracy: 0.4789
Epoch 10/35
66/66 [==============================] - 1s 14ms/step - loss: 1.5152 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.4847 - val_sparse_categorical_accuracy: 0.4789
Epoch 11/35
66/66 [==============================] - 1s 14ms/step - loss: 1.4567 - sparse_categorical_accuracy: 0.4957 - val_loss: 1.4283 - val_sparse_categorical_accuracy: 0.4789
Epoch 12/35
66/66 [==============================] - 1s 14ms/step - loss: 1.4024 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.3762 - val_sparse_categorical_accuracy: 0.4789
Epoch 13/35
66/66 [==============================] - 1s 16ms/step - loss: 1.3522 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.3280 - val_sparse_categorical_accuracy: 0.4789
Epoch 14/35
66/66 [==============================] - 1s 14ms/step - loss: 1.3058 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.2836 - val_sparse_categorical_accuracy: 0.4789
Epoch 15/35
66/66 [==============================] - 1s 15ms/step - loss: 1.2631 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.2426 - val_sparse_categorical_accuracy: 0.4789
Epoch 16/35
66/66 [==============================] - 1s 15ms/step - loss: 1.2237 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.2049 - val_sparse_categorical_accuracy: 0.4789
Epoch 17/35
66/66 [==============================] - 1s 14ms/step - loss: 1.1874 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.1702 - val_sparse_categorical_accuracy: 0.4789
Epoch 18/35
66/66 [==============================] - 1s 14ms/step - loss: 1.1541 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.1382 - val_sparse_categorical_accuracy: 0.4789
Epoch 19/35
66/66 [==============================] - 1s 14ms/step - loss: 1.1234 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.1089 - val_sparse_categorical_accuracy: 0.4789
Epoch 20/35
66/66 [==============================] - 1s 14ms/step - loss: 1.0951 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.0819 - val_sparse_categorical_accuracy: 0.4789
Epoch 21/35
66/66 [==============================] - 1s 14ms/step - loss: 1.0692 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.0570 - val_sparse_categorical_accuracy: 0.4789
Epoch 22/35
66/66 [==============================] - 1s 14ms/step - loss: 1.0453 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.0342 - val_sparse_categorical_accuracy: 0.4789
Epoch 23/35
66/66 [==============================] - 1s 14ms/step - loss: 1.0233 - sparse_categorical_accuracy: 0.5090 - val_loss: 1.0131 - val_sparse_categorical_accuracy: 0.4789
Epoch 24/35
66/66 [==============================] - 1s 14ms/step - loss: 1.0030 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9936 - val_sparse_categorical_accuracy: 0.4789
Epoch 25/35
66/66 [==============================] - 1s 14ms/step - loss: 0.9842 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9757 - val_sparse_categorical_accuracy: 0.4789
Epoch 26/35
66/66 [==============================] - 1s 15ms/step - loss: 0.9669 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9591 - val_sparse_categorical_accuracy: 0.4789
Epoch 27/35
66/66 [==============================] - 1s 14ms/step - loss: 0.9510 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9438 - val_sparse_categorical_accuracy: 0.4789
Epoch 28/35
66/66 [==============================] - 1s 14ms/step - loss: 0.9362 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9297 - val_sparse_categorical_accuracy: 0.4789
Epoch 29/35
66/66 [==============================] - 1s 14ms/step - loss: 0.9225 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9166 - val_sparse_categorical_accuracy: 0.4789
Epoch 30/35
66/66 [==============================] - 1s 14ms/step - loss: 0.9099 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.9044 - val_sparse_categorical_accuracy: 0.4789
Epoch 31/35
66/66 [==============================] - 1s 16ms/step - loss: 0.8981 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.8931 - val_sparse_categorical_accuracy: 0.4789
Epoch 32/35
66/66 [==============================] - 1s 15ms/step - loss: 0.8871 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.8825 - val_sparse_categorical_accuracy: 0.4789
Epoch 33/35
66/66 [==============================] - 1s 15ms/step - loss: 0.8770 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.8728 - val_sparse_categorical_accuracy: 0.4789
Epoch 34/35
66/66 [==============================] - 1s 14ms/step - loss: 0.8675 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.8636 - val_sparse_categorical_accuracy: 0.4789
Epoch 35/35
66/66 [==============================] - 1s 15ms/step - loss: 0.8586 - sparse_categorical_accuracy: 0.5090 - val_loss: 0.8551 - val_sparse_categorical_accuracy: 0.4789
Wall time: 36.1 s

In [25]:
loss, accuracy = model.evaluate(X_test,y_test,batch_size=batch_size)
print('test_loss: %.2f' % (loss * 100.0))  
print('test_accuracy: %.2f' % (accuracy * 100.0))

29/29 [==============================] - 0s 3ms/step - loss: 0.8551 - sparse_categorical_accuracy: 0.4789
test_loss: 85.51
test_accuracy: 47.89

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
model_probs = model.predict(X_test,batch_size=batch_size,verbose=0)
# predict crisp classes for test set
model_classes = np.argmax(model_probs,axis=1)
# reduce to 1d array
model_probs = model_probs[:, 0]
 
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, model_classes)*100
# precision tp / (tp + fp)
precision = precision_score(y_test, model_classes, average='weighted')*100
# recall: tp / (tp + fn)
recall = recall_score(y_test, model_classes, average='weighted')*100
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, model_classes, average='weighted')*100

print('Accuracy: %.2f' % accuracy)
print('F1 score: %.2f' % f1)
print('Precision: %.2f' % precision)
print('Recall: %.2f' % recall)

Accuracy: 47.89
F1 score: 31.01
Precision: 22.93
Recall: 47.89

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))